import type { Conversation, Message, RelationshipTag, Source } from "@/lib/types";

function isoDaysAgo(daysAgo: number, hour = 9, minute = 0) {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function isoHoursAgo(hoursAgo: number) {
  const d = new Date(Date.now() - hoursAgo * 60 * 60 * 1000);
  d.setSeconds(0, 0);
  return d.toISOString();
}

function msg(
  senderName: string,
  body: string,
  timestamp: string,
  senderRole?: string,
): Message {
  return { senderName, senderRole, body, timestamp };
}

function baseConversation(
  id: string,
  source: Source,
  relationshipTag: RelationshipTag,
  title: string,
  participants: string[],
  messages: Message[],
  unread: boolean,
  awaitingReply: boolean,
): Conversation {
  const last = messages[messages.length - 1];
  return {
    id,
    source,
    relationshipTag,
    title,
    participants,
    messages,
    snippet: last.body.length > 110 ? `${last.body.slice(0, 110).trim()}…` : last.body,
    lastMessageAt: last.timestamp,
    unread,
    awaitingReply,
    priorityScore: 0,
    priorityLabel: "Low",
    priorityReasons: [],
  };
}

export const seedConversations: Conversation[] = [
  baseConversation(
    "c_001",
    "gmail",
    "investor",
    "Intro + 20 min next week",
    ["You", "Maya Chen"],
    [
      msg("Maya Chen", "Thanks for the deck. Can we do 20 minutes early next week to talk through the GTM plan?", isoDaysAgo(2, 16, 10), "Investor"),
      msg("You", "Absolutely. Tuesday or Wednesday morning works well on my side. Any preference?", isoDaysAgo(2, 16, 26)),
      msg("Maya Chen", "Wednesday 9:30am PT would be ideal. If that’s tight, I can do 10:15am.", isoHoursAgo(7), "Investor"),
    ],
    true,
    true,
  ),
  baseConversation(
    "c_002",
    "slack",
    "team",
    "Decision on onboarding copy",
    ["You", "Ari", "Nina"],
    [
      msg("Ari", "We need to lock the onboarding copy today so design can finalize. Are we keeping the “unify inbox” line?", isoHoursAgo(30), "PM"),
      msg("Nina", "I’d keep it but trim the second sentence. The current one feels long in the modal.", isoHoursAgo(29), "Design"),
      msg("Ari", "If you’re good with it, I’ll ship the shorter variant and we can test later.", isoHoursAgo(28), "PM"),
    ],
    true,
    true,
  ),
  baseConversation(
    "c_003",
    "whatsapp",
    "client",
    "Contract addendum (MSA)",
    ["You", "Samir Patel"],
    [
      msg("Samir Patel", "Hey, legal sent over an addendum for the MSA. Can you confirm we’re okay with the updated SLA language?", isoDaysAgo(1, 14, 5), "Client"),
      msg("You", "Got it. I’ll review the SLA section and get back to you today.", isoDaysAgo(1, 14, 22)),
      msg("Samir Patel", "Appreciate it. We’re aiming to sign tomorrow morning if possible.", isoHoursAgo(6), "Client"),
    ],
    true,
    true,
  ),
  baseConversation(
    "c_004",
    "linkedin",
    "candidate",
    "Follow-up: Founding Engineer",
    ["You", "Jordan Lee"],
    [
      msg("Jordan Lee", "Thanks again for the call. I’m excited about the direction. What are the next steps on your side?", isoDaysAgo(3, 11, 40), "Candidate"),
      msg("You", "Great meeting you too. Next step is a technical deep-dive with our PM and a short pairing session.", isoDaysAgo(3, 12, 5)),
      msg("Jordan Lee", "Sounds good. I’m available Thu afternoon or Fri morning this week.", isoHoursAgo(22), "Candidate"),
    ],
    true,
    true,
  ),
  baseConversation(
    "c_005",
    "gmail",
    "partner",
    "Partnership: inbound from RelayWorks",
    ["You", "Elena Morozova"],
    [
      msg("Elena Morozova", "We’re exploring a partner integration around shared inbox analytics. Would you be open to a quick chat?", isoDaysAgo(4, 10, 15), "Partnerships"),
      msg("You", "Open to it. Can you share a bit more about the use case and where you’d like the integration to sit?", isoDaysAgo(4, 10, 43)),
      msg("Elena Morozova", "Use case is cross-channel reporting and routing. Happy to send a 1-pager. Are you okay with a 25 min call?", isoDaysAgo(2, 9, 20), "Partnerships"),
    ],
    false,
    true,
  ),
  baseConversation(
    "c_006",
    "slack",
    "team",
    "Bug triage: search indexing",
    ["You", "Sofia"],
    [
      msg("Sofia", "I can reproduce the search issue: messages from LinkedIn threads don’t show up. Looks like the source filter is dropping them.", isoDaysAgo(1, 17, 10), "Eng"),
      msg("You", "Thanks. Can you link the repro thread and we’ll patch it this afternoon.", isoDaysAgo(1, 17, 22)),
      msg("Sofia", "Added details in the ticket. Also, our message normalizer assumes `senderRole` exists for LinkedIn.", isoHoursAgo(9), "Eng"),
    ],
    false,
    false,
  ),
  baseConversation(
    "c_007",
    "gmail",
    "client",
    "Invoice question — March",
    ["You", "Finance @ Northlake"],
    [
      msg("Finance @ Northlake", "Hi — can you resend the March invoice with the updated PO number? Ours was entered incorrectly.", isoDaysAgo(5, 15, 0), "Accounts Payable"),
      msg("You", "Yes, I’ll resend with the corrected PO today.", isoDaysAgo(5, 15, 16)),
      msg("Finance @ Northlake", "Thanks. Please include line-item detail for the seat count as well.", isoDaysAgo(4, 9, 12), "Accounts Payable"),
    ],
    true,
    true,
  ),
  baseConversation(
    "c_008",
    "whatsapp",
    "team",
    "Shipping plan for Friday",
    ["You", "Nina"],
    [
      msg("Nina", "If we keep the AI panel collapsed by default on smaller screens, we avoid a cramped layout. Agree?", isoHoursAgo(18), "Design"),
      msg("You", "Yes. Default collapsed on <lg feels right. Add an obvious toggle.", isoHoursAgo(17)),
      msg("Nina", "Cool. I’ll update the spec and send screenshots shortly.", isoHoursAgo(16), "Design"),
    ],
    false,
    false,
  ),
  baseConversation(
    "c_009",
    "linkedin",
    "partner",
    "Intro: BrightSignal + Solo",
    ["You", "Carmen Ruiz"],
    [
      msg("Carmen Ruiz", "Saw Solo’s focus on unified communication. We work with teams on signal scoring. Would love to compare notes.", isoDaysAgo(6, 10, 35), "Partner"),
      msg("You", "Thanks Carmen. Happy to chat. What segment are you focused on right now?", isoDaysAgo(6, 11, 10)),
      msg("Carmen Ruiz", "Mostly B2B SaaS. We’ve had traction with CS teams. Are you thinking CS or sales as initial wedge?", isoDaysAgo(5, 13, 0), "Partner"),
    ],
    false,
    false,
  ),
  baseConversation(
    "c_010",
    "gmail",
    "newsletter",
    "Weekly: Product Updates Digest",
    ["You", "Product Updates"],
    [
      msg("Product Updates", "This week: new Slack canvas features, Gmail deliverability tips, and a roundup of customer support workflows.", isoDaysAgo(2, 7, 30)),
      msg("Product Updates", "Bonus: how to structure follow-ups without sounding pushy.", isoDaysAgo(2, 7, 31)),
      msg("Product Updates", "Read time: 6 minutes.", isoDaysAgo(2, 7, 32)),
    ],
    false,
    false,
  ),
  baseConversation(
    "c_011",
    "slack",
    "team",
    "QA notes for Inbox 3-pane",
    ["You", "Diego"],
    [
      msg("Diego", "QA pass: reply composer wraps correctly until ~8 lines, but the action buttons can get squeezed on 320px.", isoDaysAgo(1, 9, 45), "QA"),
      msg("You", "Good catch. We should stack buttons under the textarea on xs and keep spacing consistent.", isoDaysAgo(1, 10, 2)),
      msg("Diego", "Agreed. I’ll re-test once you land the layout change.", isoHoursAgo(12), "QA"),
    ],
    true,
    true,
  ),
  baseConversation(
    "c_012",
    "gmail",
    "investor",
    "Pricing thoughts",
    ["You", "Ethan Price"],
    [
      msg("Ethan Price", "Quick question: are you leaning usage-based or per-seat for the first year?", isoDaysAgo(8, 11, 20), "Investor"),
      msg("You", "Per-seat initially, with clear tiers. We want it to feel predictable for small teams.", isoDaysAgo(8, 11, 52)),
      msg("Ethan Price", "Makes sense. When you have it, I’d love to see the first cut of the pricing page (even internal).", isoDaysAgo(7, 8, 10), "Investor"),
    ],
    false,
    true,
  ),
  baseConversation(
    "c_013",
    "whatsapp",
    "client",
    "Access for two more teammates",
    ["You", "Lena (Pine Ridge)"],
    [
      msg("Lena (Pine Ridge)", "Can you add two more seats for our support leads? Same billing contact as before.", isoDaysAgo(3, 13, 22), "Client"),
      msg("You", "Yes. Send me their emails and I’ll provision today.", isoDaysAgo(3, 13, 35)),
      msg("Lena (Pine Ridge)", "Here: emma@ and victor@. Also, can they see conversation priority labels?", isoHoursAgo(10), "Client"),
    ],
    true,
    true,
  ),
  baseConversation(
    "c_014",
    "gmail",
    "candidate",
    "Take-home submission",
    ["You", "Priya Nair"],
    [
      msg("Priya Nair", "Sharing my take-home. I focused on deterministic ranking and a lightweight UI spec.", isoDaysAgo(2, 18, 5), "Candidate"),
      msg("Priya Nair", "Let me know if you have questions. I’m around tomorrow morning as well.", isoDaysAgo(2, 18, 6), "Candidate"),
      msg("You", "Thanks Priya. I’ll review and follow up with feedback by EOD tomorrow.", isoDaysAgo(2, 18, 20)),
    ],
    false,
    false,
  ),
  baseConversation(
    "c_015",
    "slack",
    "team",
    "Copy review: privacy note",
    ["You", "Ari"],
    [
      msg("Ari", "We need the Settings privacy note to feel calm and clear. Any edits before we ship it?", isoDaysAgo(2, 12, 0), "PM"),
      msg("You", "Keep it short and direct. No claims we can’t back up.", isoDaysAgo(2, 12, 10)),
      msg("Ari", "Perfect. I’ll use: “Your data stays under your control…”", isoDaysAgo(2, 12, 18), "PM"),
    ],
    false,
    false,
  ),
  baseConversation(
    "c_016",
    "linkedin",
    "client",
    "Customer story interview?",
    ["You", "Hannah Brooks"],
    [
      msg("Hannah Brooks", "We’re putting together a customer story series. Would you be open to a short interview about how you manage comms?", isoDaysAgo(9, 10, 5), "Client"),
      msg("You", "Open to it. What would you want to cover and what’s the timeline?", isoDaysAgo(9, 10, 33)),
      msg("Hannah Brooks", "Mostly workflow and outcomes. Timeline is flexible — aiming for late March.", isoDaysAgo(8, 9, 12), "Client"),
    ],
    false,
    false,
  ),
  baseConversation(
    "c_017",
    "gmail",
    "partner",
    "Webhook spec clarification",
    ["You", "DevRel @ LinkBridge"],
    [
      msg("DevRel @ LinkBridge", "Question on your webhook payload: do you send message bodies or only metadata?", isoDaysAgo(1, 8, 40), "DevRel"),
      msg("You", "Right now metadata + a short snippet. Full bodies can be requested with a follow-up call using scoped permissions.", isoDaysAgo(1, 9, 5)),
      msg("DevRel @ LinkBridge", "Great — can you send an example payload and the event types you support?", isoHoursAgo(13), "DevRel"),
    ],
    true,
    true,
  ),
  baseConversation(
    "c_018",
    "slack",
    "team",
    "Infra: rate limit strategy",
    ["You", "Sofia", "Ken"],
    [
      msg("Ken", "If we’re pulling Gmail + Slack in one place, we should centralize rate limit handling. Suggest a small queue with backoff.", isoDaysAgo(4, 16, 0), "Eng"),
      msg("Sofia", "Agree. Also, priority scoring should not block ingestion. It can run post-sync.", isoDaysAgo(4, 16, 20), "Eng"),
      msg("You", "Yes. MVP: ingest first, compute score on demand (Analyze inbox).", isoDaysAgo(4, 16, 35)),
    ],
    false,
    false,
  ),
  baseConversation(
    "c_019",
    "whatsapp",
    "partner",
    "Joint webinar idea",
    ["You", "Omar"],
    [
      msg("Omar", "Would you be interested in a joint webinar on cross-channel support workflows?", isoDaysAgo(7, 14, 10), "Partner"),
      msg("You", "Potentially. Who would the audience be and what’s the format?", isoDaysAgo(7, 14, 40)),
      msg("Omar", "Audience is support ops leads. 30 min talk + 15 min Q&A. We can handle promotion.", isoDaysAgo(6, 9, 25), "Partner"),
    ],
    false,
    false,
  ),
  baseConversation(
    "c_020",
    "gmail",
    "client",
    "Security questionnaire",
    ["You", "IT Security — Redwood"],
    [
      msg("IT Security — Redwood", "Attached is our security questionnaire. We need it back by Friday to proceed with procurement.", isoDaysAgo(2, 10, 0), "Security"),
      msg("You", "Received. I’ll complete the questionnaire and return it by Thursday afternoon.", isoDaysAgo(2, 10, 18)),
      msg("IT Security — Redwood", "Thanks. Please confirm whether you support SSO (SAML) and what data is stored at rest.", isoHoursAgo(20), "Security"),
    ],
    true,
    true,
  ),
  baseConversation(
    "c_021",
    "linkedin",
    "investor",
    "Quick sync before Friday",
    ["You", "David Kim"],
    [
      msg("David Kim", "Can you do a quick sync before Friday? I want to understand the roadmap after MVP.", isoDaysAgo(1, 15, 10), "Investor"),
      msg("You", "Yes. I can do Thu 11am PT or Fri 8:30am PT.", isoDaysAgo(1, 15, 30)),
      msg("David Kim", "Thu 11am PT works. Please send a calendar invite.", isoHoursAgo(5), "Investor"),
    ],
    true,
    true,
  ),
  baseConversation(
    "c_022",
    "slack",
    "team",
    "Icon set for sources",
    ["You", "Nina"],
    [
      msg("Nina", "Do we want source badges as icons or text pills? Icons may reduce scan time.", isoDaysAgo(3, 9, 0), "Design"),
      msg("You", "Text pills for MVP. Icons can come later. Make the pills consistent in width.", isoDaysAgo(3, 9, 8)),
      msg("Nina", "Got it. I’ll keep them subtle with one accent color elsewhere.", isoDaysAgo(3, 9, 12), "Design"),
    ],
    false,
    false,
  ),
  baseConversation(
    "c_023",
    "gmail",
    "newsletter",
    "Support Ops Weekly",
    ["You", "Support Ops Weekly"],
    [
      msg("Support Ops Weekly", "New: playbooks for follow-ups, handoffs, and reducing response time without burning out.", isoDaysAgo(6, 7, 10)),
      msg("Support Ops Weekly", "Case study: how a 12-person team simplified inbox triage.", isoDaysAgo(6, 7, 11)),
      msg("Support Ops Weekly", "Tip: use a single priority label system across channels.", isoDaysAgo(6, 7, 12)),
    ],
    false,
    false,
  ),
  baseConversation(
    "c_024",
    "whatsapp",
    "candidate",
    "Availability next week",
    ["You", "Alina"],
    [
      msg("Alina", "Hi! Following up on the recruiter intro. Are you still hiring for the product role?", isoDaysAgo(5, 12, 25), "Candidate"),
      msg("You", "Yes. If you’re open, send your CV and a couple of time windows next week.", isoDaysAgo(5, 12, 40)),
      msg("Alina", "Sent via email just now. I’m free Mon 2–5pm or Tue 9–11am.", isoDaysAgo(4, 9, 0), "Candidate"),
    ],
    true,
    true,
  ),
  baseConversation(
    "c_025",
    "gmail",
    "client",
    "Escalation: SLA breach question",
    ["You", "Monica — ClearSky"],
    [
      msg("Monica — ClearSky", "We saw a delayed response last week. Can you confirm how you define first response time for the SLA?", isoDaysAgo(1, 11, 0), "Client"),
      msg("You", "Yes. First response time is measured from the first inbound message to the first human reply. I’ll share details.", isoDaysAgo(1, 11, 18)),
      msg("Monica — ClearSky", "Thank you. This impacts our internal reporting, so clarity would help.", isoHoursAgo(8), "Client"),
    ],
    true,
    true,
  ),
  baseConversation(
    "c_026",
    "slack",
    "team",
    "Copy for empty state",
    ["You", "Ari"],
    [
      msg("Ari", "Empty state copy: “Select a conversation to see details.” Works?", isoDaysAgo(1, 13, 5), "PM"),
      msg("You", "Yes. Keep it exact. It’s calm and clear.", isoDaysAgo(1, 13, 12)),
      msg("Ari", "Great. I’ll ensure we use it everywhere.", isoDaysAgo(1, 13, 18), "PM"),
    ],
    false,
    false,
  ),
  baseConversation(
    "c_027",
    "linkedin",
    "partner",
    "API access question",
    ["You", "Renee Walsh"],
    [
      msg("Renee Walsh", "Do you have an API for pulling prioritized threads into our CRM workflow?", isoDaysAgo(2, 9, 40), "Partner"),
      msg("You", "Not public yet, but we can share a minimal endpoint spec for MVP partners.", isoDaysAgo(2, 10, 5)),
      msg("Renee Walsh", "That’d be great. What would you need from us to scope it?", isoDaysAgo(2, 10, 20), "Partner"),
    ],
    true,
    true,
  ),
  baseConversation(
    "c_028",
    "gmail",
    "team",
    "Internal: board update outline",
    ["You", "Ari", "Ken"],
    [
      msg("Ari", "I drafted a board update outline: wins, learnings, next risks. Want me to share it for edits?", isoDaysAgo(6, 16, 25), "PM"),
      msg("Ken", "Please share. I can add a short section on connector stability and rate limits.", isoDaysAgo(6, 16, 40), "Eng"),
      msg("You", "Yes, share it. Keep the narrative tight and avoid jargon.", isoDaysAgo(6, 16, 55)),
    ],
    false,
    false,
  ),
  baseConversation(
    "c_029",
    "whatsapp",
    "client",
    "Can we add LinkedIn to our workspace?",
    ["You", "Tracy"],
    [
      msg("Tracy", "We use LinkedIn messages a lot. Can Solo bring those into the same workspace with Gmail and Slack?", isoDaysAgo(3, 18, 0), "Client"),
      msg("You", "Yes. LinkedIn is supported in MVP. We’re keeping the connector controlled while we harden it.", isoDaysAgo(3, 18, 12)),
      msg("Tracy", "Great. Any docs you can share to help us onboard the team?", isoDaysAgo(2, 10, 40), "Client"),
    ],
    false,
    true,
  ),
  baseConversation(
    "c_030",
    "gmail",
    "newsletter",
    "Hiring newsletter",
    ["You", "Hiring Signals"],
    [
      msg("Hiring Signals", "This week’s roles: platform engineer, product designer, head of support. Plus: interview rubric templates.", isoDaysAgo(10, 7, 20)),
      msg("Hiring Signals", "Tip: follow up within 48 hours after onsite to maintain momentum.", isoDaysAgo(10, 7, 21)),
      msg("Hiring Signals", "Links inside.", isoDaysAgo(10, 7, 22)),
    ],
    false,
    false,
  ),
  baseConversation(
    "c_031",
    "slack",
    "team",
    "Roadmap: brief generation",
    ["You", "Sofia"],
    [
      msg("Sofia", "For Morning Brief, do we want it to reflect current ordering only, or also include “awaiting reply” regardless of score?", isoDaysAgo(2, 14, 5), "Eng"),
      msg("You", "Include both. Top priorities based on score, plus follow-ups where we’re awaiting reply.", isoDaysAgo(2, 14, 12)),
      msg("Sofia", "Got it. I’ll keep it deterministic and derived from the local dataset.", isoDaysAgo(2, 14, 18), "Eng"),
    ],
    false,
    false,
  ),
  baseConversation(
    "c_032",
    "linkedin",
    "candidate",
    "Checking in",
    ["You", "Marcus"],
    [
      msg("Marcus", "Hi — just checking in on the status of the role. Still interested.", isoDaysAgo(6, 12, 0), "Candidate"),
      msg("You", "Thanks Marcus. We’re still interviewing. I’ll have an update by end of week.", isoDaysAgo(6, 12, 10)),
      msg("Marcus", "Appreciate it. Happy to hop on a quick call if helpful.", isoDaysAgo(5, 9, 25), "Candidate"),
    ],
    false,
    false,
  ),
  baseConversation(
    "c_033",
    "gmail",
    "client",
    "Pilot kickoff — agenda",
    ["You", "Ravi @ Helio"],
    [
      {
        senderName: "Ravi @ Helio",
        senderRole: "Client",
        body: "For the pilot kickoff, can you share an agenda and who should attend from your side?",
        timestamp: isoDaysAgo(1, 9, 10),
        source: "linkedin",
      },
      msg(
        "You",
        "Yes. I’ll send a short agenda and suggested attendees today.",
        isoDaysAgo(1, 9, 25),
      ),
      {
        senderName: "Ravi @ Helio",
        senderRole: "Client",
        body: "Thanks. We’d like to include Support Ops and one lead from Sales.",
        timestamp: isoHoursAgo(15),
        source: "slack",
      },
    ],
    true,
    true,
  ),
  baseConversation(
    "c_034",
    "whatsapp",
    "team",
    "Small copy tweak",
    ["You", "Ari"],
    [
      msg("Ari", "Should we say “Analyze inbox” or “Analyze Inbox”? I’m leaning sentence case.", isoHoursAgo(26), "PM"),
      msg("You", "Use “Analyze inbox” exactly.", isoHoursAgo(26)),
      msg("Ari", "Done.", isoHoursAgo(25), "PM"),
    ],
    false,
    false,
  ),
  baseConversation(
    "c_035",
    "gmail",
    "partner",
    "Calendar link",
    ["You", "Mika — Orbit Partners"],
    [
      msg("Mika — Orbit Partners", "Can you send a calendar link for next week? I’m coordinating with two folks on my side.", isoDaysAgo(3, 10, 0), "Partner"),
      msg("You", "Yes. I’ll send times for Tue–Thu and we can lock one in.", isoDaysAgo(3, 10, 12)),
      msg("Mika — Orbit Partners", "Perfect. Earlier in the day is best if possible.", isoDaysAgo(2, 8, 45), "Partner"),
    ],
    false,
    true,
  ),
  baseConversation(
    "c_036",
    "linkedin",
    "client",
    "ROI question",
    ["You", "Noah Stein"],
    [
      msg("Noah Stein", "How are teams measuring ROI with Solo? Any early metrics you’re seeing?", isoDaysAgo(7, 9, 10), "Client"),
      msg("You", "Early signals: faster first response, fewer dropped threads, and clearer ownership. Happy to share a short summary.", isoDaysAgo(7, 9, 28)),
      msg("Noah Stein", "A short summary would be helpful. Thanks.", isoDaysAgo(6, 11, 5), "Client"),
    ],
    false,
    true,
  ),
  baseConversation(
    "c_037",
    "slack",
    "team",
    "Release notes",
    ["You", "Diego"],
    [
      msg("Diego", "Do you want release notes inside the app yet, or keep it out of MVP?", isoDaysAgo(5, 14, 0), "QA"),
      msg("You", "Keep it out for now. Focus on Inbox, Brief, Search, Settings polish.", isoDaysAgo(5, 14, 8)),
      msg("Diego", "Ok. I’ll remove the placeholder route.", isoDaysAgo(5, 14, 12), "QA"),
    ],
    false,
    false,
  ),
  baseConversation(
    "c_038",
    "gmail",
    "client",
    "Question about data retention",
    ["You", "Legal — Pine Ridge"],
    [
      msg("Legal — Pine Ridge", "Can you confirm your data retention policy for message content and metadata?", isoDaysAgo(2, 9, 15), "Legal"),
      msg("You", "Yes. For MVP we retain only what’s required to provide the workspace. I’ll send a concise policy summary.", isoDaysAgo(2, 9, 40)),
      msg("Legal — Pine Ridge", "Thank you. Also confirm whether you share data with third parties.", isoHoursAgo(11), "Legal"),
    ],
    true,
    true,
  ),
  baseConversation(
    "c_039",
    "whatsapp",
    "newsletter",
    "Founder digest",
    ["You", "Founder Digest"],
    [
      msg("Founder Digest", "Today: how teams run calmer communication rhythms without losing speed.", isoDaysAgo(3, 7, 5)),
      msg("Founder Digest", "Also: examples of consistent UI density in early SaaS products.", isoDaysAgo(3, 7, 6)),
      msg("Founder Digest", "Read time: 4 minutes.", isoDaysAgo(3, 7, 7)),
    ],
    false,
    false,
  ),
  baseConversation(
    "c_040",
    "linkedin",
    "investor",
    "One question on retention",
    ["You", "Aisha Rahman"],
    [
      msg("Aisha Rahman", "One question: what’s the retention loop for a unified inbox product? Where do users get repeated value?", isoDaysAgo(1, 10, 10), "Investor"),
      msg("You", "Daily: prioritization + quick drafts. Weekly: better follow-up hygiene and fewer dropped threads. Happy to expand.", isoDaysAgo(1, 10, 35)),
      msg("Aisha Rahman", "Please expand with 2–3 concrete examples. That’d help me understand the wedge.", isoHoursAgo(4), "Investor"),
    ],
    true,
    true,
  ),
];

